In [1]:
#упражнение 1

n = int(input())

def fib(n):
    if n == 0:
        return 1
    elif n == 1:
        return 1
    else:
        return fib(n-2) + fib(n-1)
print(fib(n))

5
8


In [3]:
#упражнение 2

def sf(n, a = []):
    for i in range(2, n):
        if n % i == 0:
            a.append(i)
            return sf(n//i, a)
    a.append(n)
    return a

print(*sf(int(input())))


6
2 3


In [3]:
#упражнение 3
def evklid(a, b):
    if b == 0:
        return 1, 0, a
    else:
        x_1, y_1, d = f(b, a % b)
        x = y_1
        y = x_1 - (a // b) * y_1
        return x, y, d    
    
s = list(map(int, input().split()))

print(*evklid(s[0], s[1]))        


4 6
-1 1 2


In [5]:
#упражнение 4

def tr(x, y, z = 1):
    if x % 2 != 0 and z == (x // 2 + 1):
        print(y * z)
        return
    if x % 2 == 0 and z == (x // 2):
        print(y * z)
        print(y * z)
        return
    print(y * z)

    tr(x, y, z = z + 1)

    print(y * z)
s = list(input().split())
x = int(s[0])
y = s[1]
tr(x, y)

7 c
c
cc
ccc
cccc
ccc
cc
c


In [5]:
#упраднение 5

import numpy as np

def matrix(m, n):
    a = np.zeros((m, n))
    a[0][0] = 1
    i = 0
    j = 1
    counter = 1

    while 0 in a:
        while j < n and a[i][j] == 0:
            a[i][j] = counter + 1
            counter += 1
            j += 1
        j -= 1
        i += 1

        while i < m and a[i][j] == 0:
            a[i][j] = counter + 1
            counter += 1
            i += 1
        i -= 1
        j -= 1

        while j > -1 and a[i][j] == 0:
            a[i][j] = counter + 1
            counter += 1
            j -= 1
        j += 1
        i -= 1

        while i > -1 and a[i][j] == 0:
            a[i][j] = counter + 1
            counter += 1
            i -= 1
        i += 1
        j += 1
    return a

def multiplication(first_res):
    for i in range(len(first_res)):
        first_res[i] = np.array(first_res[i]) * (i + 1)
    return first_res

data = list(map(int, input().split()))
line = data[0]
pillar = data[1]

mat = matrix(line, pillar)

print(multiplication(mat))

3 3
[[ 1.  2.  3.]
 [16. 18.  8.]
 [21. 18. 15.]]


In [6]:
#упражнение 7

-

None


In [ ]:
#упражнение 8 

-